#!/bin/bash
import ftplib

mogrify -resize 968x648 /home/pi/photobooth_images/*.jpg
montage /home/pi/photobooth_images/*.jpg -tile 2x2 -geometry +0+0 /home/pi/temp_montage2.jpg
composite -compose atop -gravity center /home/pi/temp_montage2.jpg /home/pi/photobooth_label.jpg /home/pi/temp_montage3.jpg
#lp -d Canon_CP900 /home/pi/temp_montage3.jpg
suffix=$(date +%H%M%S)
session = ftplib.FTP('coralbells.dreamhost.com','scroniser','QwQ5^$^DxQ!bq96HtGk55')
file = open('/home/pi/temp_montage3.jpg','rb')                  # file to send
session.storbinary('STOR /qfc/images/qfc-2015-${suffix}.jpg', file)     # send the file
file.close()                                                            # close file and FTP
session.quit()
cp /home/pi/temp_montage3.jpg /home/pi/PB_archive/qfc-2015-${suffix}.jpg
rm /home/pi/photobooth_images/*.jpg
rm /home/pi/temp*
